name: 'Terratest GitHub Actions'
on:
  pull_request:
    branches:
      - master
    types: [labeled]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@master


      - name: 'Terratest'
        if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v5.0'
        with:
          actions_subcommand: 'terratest_do'
          tf_actions_working_dir: '_test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DO_TOKEN:  ${{ secrets.DO_TOKEN }}


      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()