# name: 'Terraform GitHub Actions'
# on:
#   pull_request:
#     branches:
#       - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Terraform Format'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'fmt'

      - name: 'Terraform init'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example

      - name: 'Terraform validate'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example


      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()